### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

:clock10: **Full build**: the average full build time is _57 min(s) 13 sec(s)_, this is based on the last _1_ build(s) for this repository.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C21%5C849ad8c0-30cd-c102-971d-888e92cad7b5%5CPullRequest%5C202005211201384733-53%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=drmkwJwWENSGSbBAol%2F7GN96pJeb4yoseInK7MQlRzM%3D&st=2020-05-21T13%3A01%3A23Z&se=2020-06-21T13%3A06%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

:clock10: **Full build**: the average full build time is _58 min(s) 51 sec(s)_, this is based on the last _2_ build(s) for this repository.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

:clock10: **Full build**: the average full build time is _58 min(s) 51 sec(s)_, this is based on the last _2_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

:clock10: **Full build**: the average full build time is _58 min(s) 51 sec(s)_, this is based on the last _2_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5b4d4eb](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/5b4d4eb8b1bb06dafaae65dfc8dfe518ca37cca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C22%5C849ad8c0-30cd-c102-971d-888e92cad7b5%5CPullRequest%5C202005220336312615-53%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GfXi4mi0FTtaAQyIHKsTkP0LzVWaWi4yxyu0Mr8r97A%3D&st=2020-05-22T06%3A59%3A26Z&se=2020-06-22T07%3A04%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/849ad8c0-30cd-c102-971d-888e92cad7b5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
