### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[f83097c](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/f83097cf5d80dbf53c0345686ef12532f807718e)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f83097c](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/f83097cf5d80dbf53c0345686ef12532f807718e)_: 

:clock10: **Full build**: the average full build time is _33 min(s) 19 sec(s)_, this is based on the last _3_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[f83097c](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/f83097cf5d80dbf53c0345686ef12532f807718e)_: 

:clock10: **Full build**: the average full build time is _33 min(s) 19 sec(s)_, this is based on the last _3_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[f83097c](https://github.com/OPS-E2E-PPE/azure-docs-powershell/commits/f83097cf5d80dbf53c0345686ef12532f807718e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C1%5C849ad8c0-30cd-c102-971d-888e92cad7b5%5CPullRequest%5C202003010658159483-48%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ViZSRwl81KvhAoQpLzy8RWQcQVMf8ogOed5%2BKxtMvUc%3D&st=2020-03-01T08%3A05%3A10Z&se=2020-04-01T08%3A10%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
